[character]
success_symbol = "[➜](bold green)"

[kubernetes]
format = '[⛵ $context \($namespace\)](dimmed green) '
disabled = false

[kubernetes.context_aliases]
"gke_.*_(?P<cluster>[\\w-]+)" = "gke-$cluster"

[battery]
disabled = true

[golang]
disabled = true

[gcloud]
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '

[buf]
disabled = true
